version: "2.15.1"
services:
  server:
    build: ./FIRSTAPP
    container_name: test-c
    ports:
      - '3000:3000'
    volumes:
      - ./FIRSTAPP:/app
      - /app/node_modules
  database:
    image: mongo
    volumes:
      - ./database:/data/db
